"""Copernicus Data Space Ecosystem (CDSE) STAC Client.

Provides dual-mode STAC discovery:
1. Live Production: Connects to Copernicus Data Space Ecosystem STAC endpoint.
2. Offline / Mock Mode: Yields synthetic scenes generated by scripts/generate_mock_data.py
   when CAELUM_MOCK_INGEST=true or when offline.

Project Caelum-EO (github.com/FranekJemiolo/Caelum-EO)
"""

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional
import pystac_client
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger(__name__)

DEFAULT_CDSE_STAC_URL = os.getenv(
    "CDSE_STAC_API_URL", "https://catalogue.dataspace.copernicus.eu/stac"
)
MOCK_INGEST_ENV = os.getenv("CAELUM_MOCK_INGEST", "false").lower() == "true"
PRITHVI_BANDS = ["B02", "B03", "B04", "B8A", "B11", "B12"]


class STACBandMeta(BaseModel):
    band: str
    href: str
    media_type: Optional[str] = "image/tiff; application=geotiff"


class STACItemPayload(BaseModel):
    item_id: str
    collection: str
    datetime: str
    bbox: List[float]
    cloud_cover: float
    platform: str
    mgrs_tile: str
    bands: Dict[str, STACBandMeta]
    scl_href: Optional[str] = None
    is_mock: bool = False
    published_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class CDSEClient:
    """Client for querying Copernicus STAC with offline mock fallback."""

    def __init__(
        self,
        stac_url: str = DEFAULT_CDSE_STAC_URL,
        mock_mode: bool = MOCK_INGEST_ENV,
        mock_data_dir: str = "./data/mock"
    ):
        self.stac_url = stac_url
        self.mock_mode = mock_mode
        self.mock_data_dir = Path(mock_data_dir)
        self._client = None

    @property
    def client(self) -> pystac_client.Client:
        if self._client is None and not self.mock_mode:
            try:
                logger.info("Connecting to live CDSE STAC endpoint", url=self.stac_url)
                self._client = pystac_client.Client.open(self.stac_url)
            except Exception as exc:
                logger.warning(
                    "Failed to connect to CDSE STAC API; activating offline mock mode",
                    error=str(exc)
                )
                self.mock_mode = True
        return self._client

    def search_scenes(
        self,
        bbox: List[float],
        start_time: datetime,
        end_time: datetime,
        max_cloud_cover: float = 20.0,
        collection: str = "SENTINEL-2",
        limit: int = 20
    ) -> List[STACItemPayload]:
        """Query STAC items within bounding box and time window."""
        if self.mock_mode:
            logger.info("Serving synthetic mock scenes from local storage", mock_dir=str(self.mock_data_dir))
            return self._generate_mock_stac_items(bbox)

        datetime_range = f"{start_time.strftime('%Y-%m-%dT%H:%M:%SZ')}/{end_time.strftime('%Y-%m-%dT%H:%M:%SZ')}"
        try:
            search = self.client.search(
                collections=[collection],
                bbox=bbox,
                datetime=datetime_range,
                max_items=limit
            )

            results: List[STACItemPayload] = []
            for item in search.items():
                props = item.properties
                cloud = float(props.get("cloudCover", props.get("eo:cloud_cover", 0.0)))
                if cloud > max_cloud_cover:
                    continue

                bands_dict = {}
                for b in PRITHVI_BANDS:
                    # Look up band asset
                    matching_key = next((k for k in item.assets.keys() if b.upper() in k.upper()), None)
                    if matching_key:
                        bands_dict[b] = STACBandMeta(
                            band=b,
                            href=item.assets[matching_key].href,
                            media_type=item.assets[matching_key].media_type
                        )
                    else:
                        bands_dict[b] = STACBandMeta(
                            band=b,
                            href=f"https://zipper.dataspace.copernicus.eu/odata/v1/Assets({item.id}_{b})/$value"
                        )

                scl_key = next((k for k in item.assets.keys() if "SCL" in k.upper()), None)
                scl_url = item.assets[scl_key].href if scl_key else None

                mgrs = props.get("s2:mgrs_tile", props.get("mgrs:utm_zone", "34UFB"))

                payload = STACItemPayload(
                    item_id=item.id,
                    collection=collection,
                    datetime=item.datetime.isoformat() if item.datetime else datetime.now(timezone.utc).isoformat(),
                    bbox=list(item.bbox) if item.bbox else bbox,
                    cloud_cover=cloud,
                    platform=props.get("platform", "sentinel-2"),
                    mgrs_tile=str(mgrs),
                    bands=bands_dict,
                    scl_href=scl_url,
                    is_mock=False
                )
                results.append(payload)

            return results
        except Exception as exc:
            logger.warning("Error querying remote STAC; falling back to synthetic mock items", error=str(exc))
            return self._generate_mock_stac_items(bbox)

    def _generate_mock_stac_items(self, bbox: List[float]) -> List[STACItemPayload]:
        """Generate mock STAC payloads referencing locally seeded GeoTIFFs."""
        t0_dir = self.mock_data_dir / "T0_baseline"
        t1_dir = self.mock_data_dir / "T1_monitor"

        items = []
        # T0 Baseline Item
        t0_bands = {
            b: STACBandMeta(band=b, href=str((t0_dir / f"{b}.tif").absolute()))
            for b in PRITHVI_BANDS
        }
        items.append(
            STACItemPayload(
                item_id="S2A_MOCK_T0_BASELINE_20260515_34UFB",
                collection="SENTINEL-2",
                datetime="2026-05-15T08:30:00Z",
                bbox=bbox,
                cloud_cover=1.5,
                platform="Sentinel-2A",
                mgrs_tile="34UFB",
                bands=t0_bands,
                scl_href=str((t0_dir / "SCL.tif").absolute()),
                is_mock=True
            )
        )

        # T1 Monitor Item
        t1_bands = {
            b: STACBandMeta(band=b, href=str((t1_dir / f"{b}.tif").absolute()))
            for b in PRITHVI_BANDS
        }
        items.append(
            STACItemPayload(
                item_id="S2B_MOCK_T1_MONITOR_20260927_34UFB",
                collection="SENTINEL-2",
                datetime="2026-09-27T10:00:31Z",
                bbox=bbox,
                cloud_cover=2.8,
                platform="Sentinel-2B",
                mgrs_tile="34UFB",
                bands=t1_bands,
                scl_href=str((t1_dir / "SCL.tif").absolute()),
                is_mock=True
            )
        )
        return items
